version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-food-analyzer-backend
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FLASK_ENV=production
    volumes:
      # Mount models folder (since .pth files are too large for Docker image)
      - ./models:/app/models:ro
      # Mount uploads folder for persistent storage
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - food-analyzer-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-food-analyzer-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - food-analyzer-network

networks:
  food-analyzer-network:
    driver: bridge
